### ISSUE TITLE
recommend data

### ISSUE THREAD

**Issue by ducta5** [madawas/spark-recommendation#1]
Hi you
Please sent me these follow data files:

public static final String RESOURCE_PATH = "/home/madawa/WSO2/usb/data/movielens/medium/";    public static final String RATINGS_FILE_NAME = "ratings.dat";
public static final String MOVIES_FILE_NAME = "movies.dat";

Thanks 
Email: ducta.brad@gmail.com

**Comment by madawas** [comment]
You can get the data files here.
http://grouplens.org/datasets/movielens/

If you want detailed description
http://madawas.tumblr.com/post/121661638179/movie-recommendation-with-apache-spark-and-java
